---
- name: Leer archivo CSV en Ansible
  gather_facts: true
  hosts: localhost
  tasks:
    - name: Leer archivo CSV
      community.general.read_csv:
        path: "/Users/manzi/Downloads/ansible-for-i/roles/leer_archivos/archivos/datos.csv"
      register: datoscsv

    - name: Imprimir
      ansible.builtin.debug:
      loop: '{{ datoscsv.list }}'
      loop_control:
        loop_var: datoscsv
