---
- name: Consulta de RFCs o CHGs en ServiceNow
  uri:
    url: "Api de la tabla de ServiceNow"
    method: GET
    headers:
      Authorization: "Basic {{ encoded_credentials }}"
    return_content: yes
    status_code: 200
    params:
      sysparm_query: "category={{ Datos }}"  # RFC de Datos
  register: response

- name: Verificar estado de la consulta
  fail:
    msg: "Error al consultar RFCs o CHGs en ServiceNow: {{ response.status }}"
  when: response.status != 200

- name: Mostrar resultados de la consulta
  debug:
    msg: "{{ response.json }}"

- name: Descargar archivos .sql adjuntos desde ServiceNow
  gather_facts: no
  tasks:
    - name: Iterar sobre los resultados de la consulta
      ansible.builtin.include_tasks: download_task.yaml
      loop: "{{ response.json.result }}"
      loop_control:
        loop_var: item

